### ISSUE TITLE
Automatically set the sector size to be read by the bootsector

### ISSUE THREAD

**Issue by WCY-dt** [gmarino2048/64bit-os-tutorial#18]
I noticed that in `build.sh` there exists

```shell
echo "ALERT: Adjust boot sector to load $sectors sectors"
```

I think this can be automated. We can set a variable in `boot.asm` to modify, and then write the calculated size into it using `build.sh`.

**Comment by WCY-dt** [comment]
I just saw Issue #13  and I think the solution in Pull Request #19  is slightly better than just filling the field with a lot of zeros.

**Comment by gmarino2048** [comment]
Fixed by #19
