### ISSUE TITLE
GUI tutorial? (Possible Chapter 4 concept)

### ISSUE THREAD

**Issue by twisted-nematic57** [gmarino2048/64bit-os-tutorial#5]
I know you said you were focusing on other projects right now. If that still applies, go ahead and ignore this, really no issues. :)

If not, then is it possible for you to cover some kind of very very simple GUI code? I'm hopelessly lost on controlling individual pixels and  (eventually) drawing them through a physical graphics card and not the CPU because it's slow.

**Comment by gmarino2048** [comment]
Hi @HackerDaGreat57, unfortunately this is not within scope of this tutorial. For controlling a screen with legacy technologies, you can look at [this page](https://wiki.osdev.org/VGA_Resources) on the OsDev Wiki. VGA is probably your best bet for getting started with CPU graphics. Unfortunately, there are far too many types of different graphics cards for that to be feasible. Many graphics cards manufacturers (with the exception of NVIDIA) have released technical documentation or open-source drivers you can use as reference. If you're curious about it, I would recommend taking a look at AMD's open-source drivers for examples on more modern hardware.

**Comment by twisted-nematic57** [comment]
Thanks a lot for the reference, I will look into it.
